#!/usr/bin/env bash
# Release build onto a running Android emulator/device.
#
# Pins JAVA_HOME to an AGP-compatible JDK (17/21). The Android Gradle Plugin in
# RN 0.86 cannot use JDK 26 — its jlink fails to transform
# core-for-system-modules.jar — and a stock macOS dev box may only have the
# newest Temurin on PATH. Android Studio's bundled JBR is JDK 21, so prefer it.
# android/ is generated by prebuild (CNG), so this can't live in gradle.properties.
#
# Usage: scripts/build-android.sh
#   CARLIB_SEED=<seed email>  auto-signs-in that seed user (screenshot harness)
#   CARLIB_TAB=shops|profile  lands on that tab
#   CARLIB_THEME=dark|light   forces the theme mode
#   CARLIB_ANDROID_DEVICE=emulator-5556  install on that adb serial (see below)
#   CARLIB_PREBUILD=1         re-run prebuild first — REQUIRED after changing app.json
#                             icon/splash config, which run:ios/run:android do NOT refresh
set -euo pipefail

cd "$(dirname "$0")/.."

pick_jdk() {
  local candidates=(
    "/Applications/Android Studio.app/Contents/jbr/Contents/Home"
    "$(/usr/libexec/java_home -v 21 2>/dev/null || true)"
    "$(/usr/libexec/java_home -v 17 2>/dev/null || true)"
  )
  for c in "${candidates[@]}"; do
    [[ -n "$c" && -x "$c/bin/java" ]] && { echo "$c"; return; }
  done
  return 1
}

if ! JAVA_HOME="$(pick_jdk)"; then
  echo "No JDK 17/21 found. Install one (e.g. brew install --cask temurin@21)." >&2
  exit 1
fi
export JAVA_HOME
# prebuild regenerates android/ without local.properties, so Gradle needs the
# SDK from the environment.
export ANDROID_HOME="${ANDROID_HOME:-$HOME/Library/Android/sdk}"
echo "JAVA_HOME=$JAVA_HOME ($("$JAVA_HOME/bin/java" -version 2>&1 | head -1))"

if [[ -n "${CARLIB_SEED:-}" ]]; then
  {
    echo "EXPO_PUBLIC_CARLIB_SEED=$CARLIB_SEED"
    [[ -n "${CARLIB_TAB:-}" ]] && echo "EXPO_PUBLIC_CARLIB_TAB=$CARLIB_TAB"
    [[ -n "${CARLIB_THEME:-}" ]] && echo "EXPO_PUBLIC_CARLIB_THEME=$CARLIB_THEME"
  } > .env.local
  echo "seeded login: $CARLIB_SEED ${CARLIB_TAB:+(tab: $CARLIB_TAB)}"
else
  rm -f .env.local
fi

if [[ -n "${CARLIB_PREBUILD:-}" ]]; then
  LANG=en_US.UTF-8 npx expo prebuild -p android
fi

rm -rf "${TMPDIR:-/tmp}/metro-cache"

# CARLIB_ANDROID_DEVICE=<adb serial> targets one emulator when several are up
# (expo would otherwise prompt, or grab whichever AVD exists).
LANG=en_US.UTF-8 npx expo run:android --variant release --no-bundler \
  ${CARLIB_ANDROID_DEVICE:+--device "$CARLIB_ANDROID_DEVICE"}
